name: xenium-publication-env
channels:
  - defaults
dependencies:
  - pip=23.3
  - python=3.10.13
  - pip:
      - anndata==0.10.2
      - annotated-types==0.6.0
      - array-api-compat==1.4
      - asttokens==2.4.1
      - backcall==0.2.0
      - comm==0.1.4
      - contourpy==1.1.1
      - cramjam==2.7.0
      - cycler==0.12.1
      - debugpy==1.8.0
      - decorator==5.1.1
      - exceptiongroup==1.1.3
      - executing==2.0.0
      - fastparquet==2023.10.1
      - fonttools==4.43.1
      - fsspec==2023.10.0
      - h5py==3.10.0
      - imagecodecs==2023.9.18
      - imageio==2.31.6
      - ipykernel==6.26.0
      - ipython==8.16.1
      - jedi==0.19.1
      - joblib==1.3.2
      - jupyter-client==8.5.0
      - jupyter-core==5.4.0
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - llvmlite==0.41.1
      - matplotlib==3.8.0
      - matplotlib-inline==0.1.6
      - natsort==8.4.0
      - nest-asyncio==1.5.8
      - networkx==3.2
      - numba==0.58.1
      - numpy==1.26.1
      - ome-types==0.4.2
      - opencv-python==4.8.1.78
      - packaging==23.2
      - pandas==2.1.2
      - parso==0.8.3
      - patsy==0.5.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==10.0.1
      - platformdirs==3.11.0
      - prompt-toolkit==3.0.39
      - psutil==5.9.6
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pydantic==2.4.2
      - pydantic-core==2.10.1
      - pygments==2.16.1
      - pynndescent==0.5.10
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - pyzmq==25.1.1
      - scanpy==1.9.5
      - scikit-image==0.22.0
      - scikit-learn==1.3.2
      - scipy==1.11.3
      - seaborn==0.13.0
      - session-info==1.0.0
      - shapely==2.0.2
      - six==1.16.0
      - stack-data==0.6.3
      - statsmodels==0.14.0
      - stdlib-list==0.9.0
      - tbb==2021.10.0
      - threadpoolctl==3.2.0
      - tifffile==2023.9.26
      - tornado==6.3.3
      - tqdm==4.66.1
      - traitlets==5.12.0
      - typing-extensions==4.8.0
      - tzdata==2023.3
      - umap-learn==0.5.4
      - wcwidth==0.2.8
      - xsdata==23.8
